on: [push]
name: Build
jobs:
  build:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Generate self-signed cert
        run: |
          $cert = New-SelfSignedCertificate -Subject "CN=FlexConfirmMailSelfSign" -Type CodeSigningCert -CertStoreLocation "Cert:\CurrentUser\My" -NotAfter (Get-Date).AddYears(10)
          (Get-Content FlexConfirmMail.csproj) -Replace '<ManifestCertificateThumbprint>[^<]*',("<ManifestCertificateThumbprint>" + $cert.Thumbprint) | Set-Content FlexConfirmMail.csproj
      - name: Compile
        run: |
          cp Global.public.cs Global.cs
          msbuild /p:Configuration=Release
      - name: Make Installer
        run: iscc.exe FlexConfirmMail.iss
      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: Installer
          path: dest/*.exe
